name = "unenv-worker"
main = "worker.mjs"
compatibility_flags = [
  "experimental",
  "nodejs_compat",
  "enable_nodejs_fs_module",
  "enable_nodejs_os_module",
  "enable_nodejs_http_server_modules",
  "enable_nodejs_http_modules",
  "enable_nodejs_process_v2"
]
compatibility_date = "2025-09-02"
